language: python
python:
  - '3.11'

install:
  - sudo apt-get update -q
  - sudo pip3 install flake8 chess aiohttp

script:
  - flake8 boards.py --ignore=F401,E501
  - flake8 lib/ --ignore=E501
  - python3 boards.py test
